# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload bnc to PyPi (testnet)

on:
  push:
    tags:
    - '*'

env:
  BNC_SETUP_PKG_NAME: bnc-testnet
  BNC_SETUP_PKG_VERSION: ''

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Get tag version and set to BNC_SETUP_PKG_VERSION env variable 
      id: get_version
      run: echo BNC_SETUP_PKG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Copy config.json
      run: |
        cp -T testnet/config.json bnc/config.json
    - name: Rename bnc folder
      run: |
        mv bnc bnc_testnet
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        python -m pip install --upgrade twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        python -m twine upload dist/*
